runtime: nodejs
env: flex
instance_class: F1
entrypoint: npm start
env_variables:
  NODE_ENV: production
automatic_scaling:
  min_num_instances: 0
  max_num_instances: 5
runtime_config:
  operating_system: "ubuntu22"
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
network:
  forwarded_ports:
    - 8000