options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Use Buildpacks to build and tag the application
  - name: 'gcr.io/buildpacks/builder'
    args:
      [
        '--builder=gcr.io/buildpacks/builder:v1',
        '--path=.',
        '--tag=gcr.io/399110791427/jessepiccione-frontend:$COMMIT_SHA'
      ]
    secretEnv: ['REACT_APP_BACKEND_API_TOKEN', 'REACT_APP_BACKEND_API_URL']

# Secrets available during the build
availableSecrets:
  secretManager:
    - versionName: projects/399110791427/secrets/REACT_APP_BACKEND_API_URL/versions/1
      env: REACT_APP_BACKEND_API_URL
    - versionName: projects/399110791427/secrets/REACT_APP_BACKEND_API_TOKEN/versions/1
      env: REACT_APP_BACKEND_API_TOKEN

# Push the built image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/399110791427/jessepiccione-frontend:$COMMIT_SHA']
images:
  - 'gcr.io/399110791427/jessepiccione-frontend:$COMMIT_SHA'