options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run','build']
    secretEnv: ['REACT_APP_BACKEND_API_TOKEN', 'REACT_APP_BACKEND_API_URL']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','.','-t','jessepiccione-frontend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/jessepiccione-info-frontend/jessepiccione-frontend']
availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/REACT_APP_BACKEND_API_URL/versions/1'
      env: 'REACT_APP_BACKEND_API_URL'
    - versionName: 'projects/$PROJECT_ID/secrets/REACT_APP_BACKEND_API_TOKEN/versions/1'
      env: 'REACT_APP_BACKEND_API_TOKEN'
images:
  - 'gcr.io/$PROJECT_ID/jessepiccione-frontend'