steps:
  - name: 'gcr.io/buildpacks/builder'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA', '.']
    secretEnv: ['REACT_APP_BACKEND_API_TOKEN', 'REACT_APP_BACKEND_API_URL']
availableSecrets:
  secretManager:
    - versionName: projects/${PROJECT_ID}/secrets/REACT_APP_BACKEND_API_URL/versions/latest
      env: REACT_APP_BACKEND_API_URL
    - versionName: projects/${PROJECT_ID}/secrets/REACT_APP_BACKEND_API_TOKEN/versions/latest 
      env: REACT_APP_BACKEND_API_TOKEN
images: 
  - 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA' 