options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run','build']
    secretEnv: ['REACT_APP_BACKEND_API_TOKEN', 'REACT_APP_BACKEND_API_URL']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build','.','-t','gcr.io/$PROJECT_ID/jessepiccione-frontend:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/jessepiccione-frontend:$BUILD_ID']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'jessepiccione', '--image', 'gcr.io/$PROJECT_ID/jessepiccione-frontend:$BUILD_ID']
availableSecrets:
  secretManager:
    - versionName: 'projects/$PROJECT_ID/secrets/REACT_APP_BACKEND_API_URL/versions/1'
      env: 'REACT_APP_BACKEND_API_URL'
    - versionName: 'projects/$PROJECT_ID/secrets/REACT_APP_BACKEND_API_TOKEN/versions/1'
      env: 'REACT_APP_BACKEND_API_TOKEN'
images:
  - 'gcr.io/$PROJECT_ID/jessepiccione-frontend:$BUILD_ID'