options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/buildpacks/builder:latest'
    args: ['build', '-t', 'gcr.io/399110791427/jessepiccione-frontend:$COMMIT_SHA', '.']
    secretEnv: ['REACT_APP_BACKEND_API_TOKEN', 'REACT_APP_BACKEND_API_URL']
availableSecrets:
  secretManager:
    - versionName: projects/399110791427/secrets/REACT_APP_BACKEND_API_URL/versions/1
      env: REACT_APP_BACKEND_API_URL
    - versionName: projects/399110791427/secrets/REACT_APP_BACKEND_API_TOKEN/versions/1
      env: REACT_APP_BACKEND_API_TOKEN
images: 
  - 'gcr.io/39911791427/jessepiccione-frontend:$COMMIT_SHA' 