options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/buildpacks/builder'
    args: ['build', '-t', 'gcr.io/jessepiccione-info-frontend/production:$COMMIT_SHA', '.']
    secretEnv: ['REACT_APP_BACKEND_API_TOKEN', 'REACT_APP_BACKEND_API_URL']
availableSecrets:
  secretManager:
    - versionName: projects/399110791427/secrets/REACT_APP_BACKEND_API_URL/versions/latest
      env: REACT_APP_BACKEND_API_URL
    - versionName: projects/399110791427/secrets/REACT_APP_BACKEND_API_TOKEN/versions/latest
      env: REACT_APP_BACKEND_API_TOKEN
images: 
  - 'gcr.io/$PROJECT_ID/production:$COMMIT_SHA' 